FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir requests boto3

COPY test_full_flow.py /app/test_full_flow.py
COPY test_load.py /app/test_load.py
COPY test-data /app/test-data

CMD ["python", "/app/test_full_flow.py"]