sonar.projectKey=tech-challenge
sonar.projectName=tech-challenge
sonar.sourceEncoding=UTF-8

# Código de produção
sonar.sources=app

# Testes
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

# Coverage (pytest-cov)
sonar.python.coverage.reportPaths=app/coverage.xml

# Ignorar arquivos que não são regra de negócio
sonar.exclusions=**/__init__.py,**/alembic/**,**/migrations/**

sonar.python.version=3.12
