import json

import pika

from app.core.config import settings


class RabbitMQConnection:
    def __init__(self):
        self.credentials = pika.PlainCredentials(
            settings.RABBITMQ_USERNAME,
            settings.RABBITMQ_PASSWORD,
        )

        self.parameters = pika.ConnectionParameters(
            host=settings.RABBITMQ_HOST,
            port=settings.RABBITMQ_PORT,
            credentials=self.credentials,
        )

    def connect(self):
        return pika.BlockingConnection(self.parameters)


class RabbitMQInitializer:
    """
    Responsible for creating the queues owned by the API.

    The Worker must not create queues.
    It only consumes queues previously created by the API.
    """

    def __init__(self):
        self.connection = RabbitMQConnection()

    def initialize(self) -> None:
        connection = self.connection.connect()

        try:
            channel = connection.channel()

            queues = [
                settings.RABBITMQ_QUEUE,
                settings.RABBITMQ_COMPLETED_QUEUE,
                settings.RABBITMQ_FAILED_QUEUE,
            ]

            for queue in queues:
                channel.queue_declare(
                    queue=queue,
                    durable=True,
                )

        finally:
            connection.close()


class RabbitMQPublisher:
    def __init__(self):
        self.connection = RabbitMQConnection()

    def publish(
        self,
        message: dict,
        queue: str | None = None,
    ) -> None:
        target_queue = queue or settings.RABBITMQ_QUEUE

        connection = self.connection.connect()

        try:
            channel = connection.channel()

            channel.basic_publish(
                exchange="",
                routing_key=target_queue,
                body=json.dumps(message),
                properties=pika.BasicProperties(
                    delivery_mode=2,
                    content_type="application/json",
                ),
            )

        finally:
            connection.close()


class RabbitMQConsumer:
    """
    Consumes processing result events generated by the Worker.

    The API creates the queues.
    The consumer only verifies that the queues exist.
    """

    def __init__(self):
        self.connection = RabbitMQConnection()

    def consume_results(
        self,
        completed_callback,
        failed_callback,
    ) -> None:
        connection = self.connection.connect()

        try:
            channel = connection.channel()

            # The API owns the queues.
            # passive=True means the consumer does not create them.
            channel.queue_declare(
                queue=settings.RABBITMQ_COMPLETED_QUEUE,
                durable=True,
                passive=True,
            )

            channel.queue_declare(
                queue=settings.RABBITMQ_FAILED_QUEUE,
                durable=True,
                passive=True,
            )

            channel.basic_qos(
                prefetch_count=1,
            )

            channel.basic_consume(
                queue=settings.RABBITMQ_COMPLETED_QUEUE,
                on_message_callback=completed_callback,
                auto_ack=False,
            )

            channel.basic_consume(
                queue=settings.RABBITMQ_FAILED_QUEUE,
                on_message_callback=failed_callback,
                auto_ack=False,
            )

            channel.start_consuming()

        finally:
            connection.close()
